/* eslint-disable max-len */
export const seedData = {
  users: {
    _model: "User",
    paintingGandalf: {
      firstName: "David",
      lastName: "Schmidt",
      username: "PaintingGandalf",
      email: "david_schmidt_privat@outlook.com",
      password: "password123",
      rank: 1,
      image: "https://cdn0.iconfinder.com/data/icons/famous-character-vol-2-colored/48/JD-41-512.png",
    },
    vader: {
      firstName: "Darth",
      lastName: "Vader",
      username: "DarkVader",
      email: "vader@imperium.com",
      password: "secret",
      rank: 2,
      image:
        "https://icons-for-free.com/download-icon-vader+darth+vader+lord+sith+lord+sith+sith+star+wars+strar+wars-1320190551463123211_512.png",
    },
    luke: {
      firstName: "Luke",
      lastName: "Skywalker",
      username: "LukeSkywalker",
      email: "skywalker@rebels.com",
      password: "secret",
      rank: 1,
      image: "https://icons-for-free.com/download-icon-jedi+luke+skywalker+star+wars+icon-1320166754665357445_512.png",
    },
    solo: {
      firstName: "Han",
      lastName: "Solo",
      username: "HanSolo",
      email: "HanSolot@rebels.com",
      password: "secret",
      rank: 0,
      image: "https://cdn4.iconfinder.com/data/icons/famous-characters-add-on-vol-1-flat/48/Famous_Character_-_Add_On_1-45-512.png",
    },
    yoda: {
      firstName: "Master",
      lastName: "Yoda",
      username: "Yoda",
      email: "MasterYoda@rebublic.com",
      password: "secret",
      rank: 1,
      image:
        "https://icons-for-free.com/download-icon-jedi+master+starwars+yoda+icon-1320166700243190687_512.png",
    },
    r2d2: {
      firstName: "R2-",
      lastName: "D2#",
      username: "R2D2",
      email: "r2d2@rebels.com",
      password: "secret",
      rank: 0,
      image: "https://cdn0.iconfinder.com/data/icons/famous-character-vol-1-colored/48/JD-39-512.png",
    },
    c3po: {
      firstName: "C-3",
      lastName: "PO#",
      username: "C-3PO",
      email: "C-3PO@rebublic.com",
      password: "secret",
      rank: 0,
      image: "https://w7.pngwing.com/pngs/51/360/png-transparent-c3po-r2d2-robot-starwars-famous-character-colored-icon-thumbnail.png",
    },
    boba: {
      firstName: "Boba",
      lastName: "Fett",
      username: "BobaFett",
      email: "bobdafett@rebels.com",
      password: "secret",
      rank: 0,
      image: "https://cdn4.iconfinder.com/data/icons/heroes-villains-vol-1-colored/100/Boba_Fett-512.png",
    },
  },
  artists: {
    _model: "Artist",
    vanGogh: {
      firstName: "Vincent",
      lastName: "van Gogh",
      description: "Vincent van Gogh was a Dutch painter, generally considered to be the greatest after Rembrandt van Rijn, and one of the greatest of the PostImpressionists. He sold only one artwork during his life, but in the century after his death he became perhaps the most recognized painter of all time.",
      image: "https://image.geo.de/30044996/t/qU/v3/w1440/r1.5/-/vincent-van-gogh-gross-jpg--18879-.jpg",
      user: "->users.luke",
    },
    daVinci: {
      firstName: "Leonardo",
      lastName: "da Vinci",
      description: "Leonardo da Vinci was an artist and engineer who is best known for his paintings, notably the Mona Lisa (c. 1503–19) and the Last Supper (1495–98). His drawing of the Vitruvian Man (c. 1490) has also become a cultural icon. Leonardo is sometimes credited as the inventor of the tank, helicopter, parachute, and flying machine, among other vehicles and devices, but later scholarship has disputed such claims. Nonetheless, Leonardo's notebooks reveal a sharp intellect, and his contributions to art, including methods of representing space, threedimensional objects, and the human figure, cannot be overstated.",
      image: "https://img.br.de/99371165-1480-494a-96fa-200ef051058c.jpeg?width=210&q=85",
      user: "->users.luke",
    },
    picasso: {
      firstName: "Pablo",
      lastName: "Picasso",
      description: "Pablo Picasso, in full Pablo Diego José Francisco de Paula Juan Nepomuceno Crispín Crispiniano María Remedios de la Santísima Trinidad Ruiz Picasso, also called (before 1901) Pablo Ruiz or Pablo Ruiz Picasso, (born October 25, 1881, Málaga, Spain—died April 8, 1973, Mougins, France), Spanish expatriate painter, sculptor, printmaker, ceramicist, and stage designer, one of the greatest and mostinfluential artists of the 20th century and the creator (with Georges Braque) of Cubism. (For more information on Picasso's name see Researcher's Note: Picasso's full name. The enormous body of Picasso's work remains, and the legend lives on—a tribute to the vitality of the “disquieting” Spaniard with the “sombre…piercing” eyes who superstitiously believed that work would keep him alive. For nearly 80 of his 91 years, Picasso devoted himself to an artistic production that contributed significantly to and paralleled the whole development of modern art in the 20th century.",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/513px-Pablo_picasso_1.jpg",
      user: "->users.luke",
    },
    rembrandt: {
      firstName: "Rembrandt",
      lastName: "Harmenszoon van Rijn",
      description: "Rembrandt, in full Rembrandt Harmenszoon van Rijn, Rembrandt originally spelled Rembrant, (born July 15, 1606, Leiden, Netherlands—died October 4, 1669, Amsterdam), Dutch Baroque painter and printmaker, one of the greatest storytellers in the history of art, possessing an exceptional ability to render people in their various moods and dramatic guises. Rembrandt is also known as a painter of light and shade and as an artist who favoured an uncompromising realism that would lead some critics to claim that he preferred ugliness to beauty. Early in his career and for some time, Rembrandt painted mainly portraits. Although he continued to paint—and etch and, occasionally, draw—portraits throughout his career, he did so less frequently over time. Roughly one-tenth of his painted and etched oeuvre consists of studies of his own face as well as more-formal self-portraits, a fact that has led to much speculation.",
      image: "https://2ho4f5klzmi1xz49c18txd0p-wpengine.netdna-ssl.com/wp-content/uploads/cache/images/ARTat-Berlin-Der-Mann-mit-dem-Goldhelm-Rembrandt-bzw-seinem-Kreis-zugeschrieben/ARTat-Berlin-Der-Mann-mit-dem-Goldhelm-Rembrandt-bzw-seinem-Kreis-zugeschrieben-2047744970.jpg",
      user: "->users.vader",
    },
    monet: {
      firstName: "Oscar-Claude",
      lastName: "Monet",
      description: "Claude Monet is a French painter known for his significant contribution to the Impressionist art movement. Born in Paris on November 14, 1840, he spent his childhood in the city of Havre (Normandy) where his family moved when he was five years old. Monet developed his passion over time, starting with caricature and then, encouraged by his father, painting, which he studied in Paris in 1859 at the Swiss Academy. Monet’s military service in Algeria in 1861 cut short his studies but he nonetheless continued to experiment with different artistic forms. Forced to return to Paris in 1862 following an illness he contracted (pleurisy), Monet met the Swiss painter Charles Gleyre and also worked with Alfred Sisley, Auguste Renoir and Frédéric Basille who all become his close friends.",
      image: "https://cdn.pariscityvision.com/library/image/5094.jpg",
      user: "->users.paintingGandalf",
    },
  },
  epochs: {
    _model: "Epoch",
    postImpressionism: {
      name: "Post-Impressionism",
      description:
        "Post-Impressionism, in Western painting, movement in France that represented both an extension of Impressionism and a rejection of that style’s inherent limitations. The term Post-Impressionism was coined by the English art critic Roger Fry for the work of such late 19th-century painters as Paul Cézanne, Georges Seurat, Paul Gauguin, Vincent van Gogh, Henri de Toulouse-Lautrec, and others. All of these painters except van Gogh were French, and most of them began as Impressionists; each of them abandoned the style, however, to form his own highly personal art. Impressionism was based, in its strictest sense, on the objective recording of nature ...",
      yearSpan: "1890 - 1920",
      image: "https://www.kunstnet.de/w2/33533/gross_on-the-road-again.jpg",
      user: "->users.vader",
    },
    renaissance: {
      name: "Renaissance",
      description:
        "Renaissance art, painting, sculpture, architecture, music, and literature produced during the 14th, 15th, and 16th centuries in Europe under the combined influences of an increased awareness of nature, a revival of classical learning, and a more individualistic view of man. Scholars no longer believe that the Renaissance marked an abrupt break with medieval values, as is suggested by the French word renaissance, literally “rebirth.” Rather, historical sources suggest that interest in nature, humanistic learning, and individualism were already present in the late medieval period and became dominant in 15th- and 16th-century Italy concurrently with social and economic changes such as the secularization of daily life, the rise of a rational money-credit economy, and greatly increased social mobility.",
      yearSpan: "14th - 17th century",
      image: "https://d1g9li960vagp7.cloudfront.net/wp-content/uploads/2021/12/shutterstock_2043241274-1024x684.jpg",
      user: "->users.vader",
    },
    cubism: {
      name: "Cubism",
      description:
        "Cubism, highly influential visual arts style of the 20th century that was created principally by the artists Pablo Picasso and Georges Braque in Paris between 1907 and 1914. The Cubist style emphasized the flat, two-dimensional surface of the picture plane, rejecting the traditional techniques of perspective, foreshortening, modeling, and chiaroscuro and refuting time-honoured theories that art should imitate nature. Cubist painters were not bound to copying form, texture, colour, and space. Instead, they presented a new reality in paintings that depicted radically fragmented objects. Cubism derived its name from remarks that were made by the critic Louis Vauxcelles, who derisively described Braque’s 1908 work Houses at L’Estaque as being composed of cubes. In Braque’s painting, the volumes of the houses, the cylindrical forms of the trees, and the tan-and-green colour scheme are reminiscent of Paul Cézanne’s landscapes, which deeply inspired the Cubists in their first stage of development (until 1909). It was, however, Les Demoiselles d’Avignon, painted by Picasso in 1907, that presaged the new style; in this work, the forms of five female nudes become fractured, angular shapes. As in Cézanne’s art, perspective is rendered through colour, with the warm reddish-browns advancing and the cool blues receding.",
      yearSpan: "1908 - 1929",
      image:
        "https://austria-forum.org/attach/Geography/Europe/Spain/Pictures/Barcelona_1/Painting_by_Picasso_-_Cubism_1/scaled-900x600-ba076d_Kubismus_2.jpg",
      user: "->users.vader",
    },
    baroque: {
      name: "Baroque",
      description:
        "Baroque art and architecture, the visual arts and building design and construction produced during the era in the history of Western art that roughly coincides with the 17th century. The earliest manifestations, which occurred in Italy, date from the latter decades of the 16th century, while in some regions, notably Germany and colonial South America, certain culminating achievements of Baroque did not occur until the 18th century. The work that distinguishes the Baroque period is stylistically complex, even contradictory. In general, however, the desire to evoke emotional states by appealing to the senses, often in dramatic ways, underlies its manifestations. Some of the qualities most frequently associated with the Baroque are grandeur, sensuous richness, drama, vitality, movement, tension, emotional exuberance, and a tendency to blur distinctions between the various arts.",
      yearSpan: "16th - 18th century",
      image: "https://static.educalingo.com/img/en/800/baroque.jpg",
      user: "->users.vader",
    },
    impressionism: {
      name: "Impressionism",
      description:
        "Impressionism, French Impressionnisme, a major movement, first in painting and later in music, that developed chiefly in France during the late 19th and early 20th centuries. Impressionist painting comprises the work produced between about 1867 and 1886 by a group of artists who shared a set of related approaches and techniques. The most conspicuous characteristic of Impressionism in painting was an attempt to accurately and objectively record visual reality in terms of transient effects of light and colour. In music, it was to convey an idea or affect through a wash of sound rather than a strict formal structure.",
      yearSpan: "c.1867 - c. 1886",
      image:
        "https://cdn.britannica.com/34/3734-004-D66E6719/canvas-oil-Le-Moulin-de-la-Galette-1876.jpg?w=400&h=300&c=crop",
      user: "->users.paintingGandalf",
    },
  },
  galleries: {
    _model: "Gallery",
    vanGoghMuseum: {
      name: "Van Gogh Museum",
      lat: 52.358353,
      lng: 4.880563,
      countAllVisitors: 2130,
      countCurVisitors: 8,
      user: "->users.luke",
    },
    rijksmuseum: {
      name: "Rijksmuseum",
      lat: 52.359438,
      lng: 4.884338,
      countAllVisitors: 200,
      countCurVisitors: 3,
      user: "->users.vader",
    },
    museuPicasso: {
      name: "MuseuPicasso",
      lat: 41.3851942030676,
      lng: 2.1808341153497857,
      countAllVisitors: 80,
      countCurVisitors: 4,
      user: "->users.vader",
    },
    louvres: {
      name: "Louvres",
      lat: 49.04295293064281,
      lng: 2.5065192561463028,
      countAllVisitors: 2000,
      countCurVisitors: 5,
      user: "->users.vader",
    },
    museeMonet: {
      name: "Musée Monet",
      lat: 48.85937569652431,
      lng: 2.2672324045852514,
      countAllVisitors: 300,
      countCurVisitors: 3,
      user: "->users.paintingGandalf",
    },
    accademia: {
      name: "Gallerie Accademia",
      lat: 45.431225176100945,
      lng: 12.328160862946914,
      countAllVisitors: 200,
      countCurVisitors: 2,
      user: "->users.paintingGandalf",
    },
  },
  posts: {
    _model: "Post",
    one: {
      headline: "The artist just had ONE ear!",
      comment:
        "Very impressive exhibition! The pictures are super presented. Also the curriculum vitae of the artist is well presented.Also very interesting how the pictures are secured",
      time: new Date("2016-05-18T16:00:00Z"),
      rating: 5,
      user: "->users.vader",
      gallery: "->galleries.vanGoghMuseum",
    },
    two: {
      headline: "Overtrumps with Donald get me Goosebumps😇",
      comment:
        "The museum is a clear must for every Amsterdam visitor! There is so much to see on different floors, you would need several hours to really look at everything in detail and read through! Of course, you have to be aware that it is very crowded inside and you sometimes have to wait to be able to read through a picture or a description. Especially before the night watch you have to fight for your slot. Also the museum garden and the library are dreamlike!❤️🌷",
      time: new Date(),
      rating: 4,
      user: "->users.paintingGandalf",
      gallery: "->galleries.vanGoghMuseum",
    },
    three: {
      headline: "Hot museum staff🙊!",
      comment:
        "Attention masks compulsory in the complete art exhibition including toilets!!! Admission of € 12.00 justified. Reduced for students and pensioners. Control of body temperature at the entrance. Large exhibition of pictorial art. Description at the beginning only Italian, in the course also English. Photography allowed, without charge. Get small guide at entrance, helps. Signage in the exhibition good, could be better in some places. Temparated rooms and almost everything accessible by wheelchair or walker. Literature available for purchase in vestibule. Limited with children as tour takes long by interest. I would recommend.",
      time: new Date("2013-05-18T16:00:00Z"),
      rating: 4,
      user: "->users.luke",
      gallery: "->galleries.accademia",
    },
    four: {
      headline: "Life is filled with secrets. You can’t learn them all at once.✅",
      comment:
        "Even if, like me, has less to do with painting and especially church painting, there are some works on display in the Academia, before which one pauses impressed.❤️🌷",
      time: new Date(),
      rating: 4,
      user: "->users.solo",
      gallery: "->galleries.accademia",
    },
    five: {
      headline: "Telling someone about what a symbol means is like telling someone how music should make them feel.",
      comment:
        "Of course, one of the museum highlights of Venice with some of the most beautiful paintings of Venetian painters ever.\
        More one would not have to say actually.\
        But the extraordinary palazzo in which the exhibition rooms are located from the inside is also worth a look! And for lovers of Hieronymus Bosch, there are 4 particularly beautiful pieces in an adjoining room. Not to be missed!",
      time: new Date("2014-05-18T16:00:00Z"),
      rating: 5,
      user: "->users.yoda",
      gallery: "->galleries.accademia",
    },
    six: {
      headline: "Overtrumps with Donald get me Goosebumps😇",
      comment:
        "Unfortunately, the toll-free number for reservations is not available today: After several attempts, the service is discontinued when the legal obligations to protect privacy are confirmed. Three free phone calls.❌😯",
      time: new Date(),
      rating: 1,
      user: "->users.paintingGandalf",
      gallery: "->galleries.accademia",
    },
    seven: {
      headline: "Faith – acceptance of which we imagine to be true, that which we cannot prove.",
      comment:
        "Only for people who are also really interested in Van Gogh and have dealt with it before. Pictures hang lovelessly on the walls and are not informative or subtitled only with typical Wikipedia (- title, painter and exhibition location and that's all obvious!), Quiet to look at pictures you also do not have, because all visitors in a single row as on a treadmill trudge through the museum and push each other on.\
        For even more information, there is the audio guide for 5 euros in addition to the 17 euros entrance fee. In my opinion, way too expensive for although many pictures, but just not a nice atmosphere.\
        There is a plus point for the organized checkroom, but that's it.\
        Rather in the Rembrandthuis, which is worth more!",
      time: new Date("2015-12-12T16:00:00Z"),
      rating: 1,
      user: "->users.r2d2",
      gallery: "->galleries.vanGoghMuseum",
    },
    eight: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The Van Gogh Museum was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.c3po",
      gallery: "->galleries.vanGoghMuseum",
    },
    nine: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The louvres was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.boba",
      gallery: "->galleries.louvres",
    },
    ten: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The louvres was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.r2d2",
      gallery: "->galleries.museeMonet",
    },
    eleven: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The louvres was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.solo",
      gallery: "->galleries.museeMonet",
    },
    twelve: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The louvres was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.r2d2",
      gallery: "->galleries.museuPicasso",
    },
    thirteen: {
      headline: "Today is today. But there are many tomorrows.😱",
      comment:
        "The louvres was definitely worth a visit. A very extensive collection of his works and also a lot of biographical information from his letters.  To see his paintings live once, should undertake everyone who visits the city. Due to the mass of objects, it is also worth visiting the museum several times.🥳 The museum was very busy and it was not always possible to keep the distance.〽",
      time: new Date("2022-06-05T16:00:00Z"),
      rating: 5,
      user: "->users.paintingGandalf",
      gallery: "->galleries.rijksmuseum",
    },
  },
  paintings: {
    _model: "Painting",
    starryNight: {
      title: "Starry Night",
      year: 1889,
      price: 70000000,
      epoch: "->epochs.postImpressionism",
      artist: "->artists.vanGogh",
      gallery: "->galleries.vanGoghMuseum",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1200px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
      user: "->users.boba",
    },
    theNightWatch: {
      title: "The Night Watch",
      year: 1642,
      price: 1300000,
      epoch: "->epochs.baroque",
      artist: "->artists.rembrandt",
      gallery: "->galleries.rijksmuseum",
      image: "https://static.dw.com/image/45910106_303.jpg",
      user: "->users.r2d2",
    },
    cryingWoman: {
      title: "Crying Woman",
      year: 1937,
      price: 2000000,
      epoch: "->epochs.cubism",
      artist: "->artists.picasso",
      gallery: "->galleries.museuPicasso",
      image: "https://m.media-amazon.com/images/I/81sO8PzFu5L._AC_SL1200_.jpg",
      user: "->users.solo",
    },
    monaLisa: {
      title: "Mona Lisa",
      year: 1503,
      price: 100000000,
      epoch: "->epochs.renaissance",
      artist: "->artists.daVinci",
      gallery: "->galleries.louvres",
      image: "https://assets.deutschlandfunk.de/FILE_2c4276cd45e7fad69bb51faa9066c4b5/1920x1080.jpg?t=1597511485777",
      user: "->users.solo",
    },
    dejeuner: {
      title: "Sunrise",
      year: 1874,
      price: 2098092,
      epoch: "->epochs.impressionism",
      artist: "->artists.monet",
      gallery: "->galleries.museeMonet",
      image: "https://impressionistarts.com/assets/claude-monet-impression-sunrise.jpg",
      user: "->users.yoda",
    },
    gare: {
      title: "Gare Saint-Lazare",
      year: 1877,
      price: 10000,
      epoch: "->epochs.impressionism",
      artist: "->artists.monet",
      gallery: "->galleries.museeMonet",
      image: "https://impressionistarts.com/assets/claude-monet-gare-saint-lazare-1877.jpg",
      user: "->users.paintingGandalf",
    },
    bordigahera: {
      title: "Bordighera ",
      year: 1883,
      price: 1800000,
      epoch: "->epochs.impressionism",
      artist: "->artists.monet",
      gallery: "->galleries.museeMonet",
      image: "https://impressionistarts.com/assets/claude-monet-bordighera.jpg",
      user: "->users.r2d2",
    },
    lilies: {
      title: "Water Lilies",
      year: 1889,
      price: 8500000,
      epoch: "->epochs.impressionism",
      artist: "->artists.monet",
      gallery: "->galleries.museeMonet",
      image: "https://impressionistarts.com/assets/claude-monet-giverny-water-lilies.jpg",
      user: "->users.c3po",
    },
    lastSupper: {
      title: "Last Supper",
      year: 1498,
      price: 85000000,
      epoch: "->epochs.renaissance",
      artist: "->artists.daVinci",
      gallery: "->galleries.louvres",
      image: "https://cdn.britannica.com/04/95904-050-7EB39FC8/Last-Supper-wall-painting-restoration-Leonardo-da-1999.jpg?q=60",
      user: "->users.yoda",
    },
    man: {
      title: "Vitruvian Man",
      year: 1490,
      price: 8500000,
      epoch: "->epochs.renaissance",
      artist: "->artists.daVinci",
      gallery: "->galleries.accademia",
      image: "https://cdn.britannica.com/68/145968-050-01768DAD/Vitruvian-Man-Leonardo-da-Vinci-Gallerie-dellAccademia.jpg?q=60",
      user: "->users.solo",
    },
    selfPortrait: {
      title: "Self Portrait",
      year: 1516,
      price: 91000,
      epoch: "->epochs.renaissance",
      artist: "->artists.daVinci",
      gallery: "->galleries.accademia",
      image: "https://cdn.britannica.com/75/115475-050-9F9B00CE/Self-portrait-drawing-Leonardo-da-Vinci-Royal-Library.jpg?q=60",
      user: "->users.vader",
    },
  },
};
